### PR TITLE
Add shop button, improve button design

### PR DESCRIPTION
**Pull request by Xpirix**
Proposed fix for https://github.com/qgis/QGIS-Hugo/issues/315

Desktop:

image

Mobile:

image

### CODE REVIEW

**Comment by Xpirix** [comment]
@timlinux, How about hiding it initially and showing the text when hovering it?

https://github.com/user-attachments/assets/de7d89a2-5e37-4947-a25f-1246b063995a

**Comment by timlinux** [comment]
LGTM - how about you @anitagraser

**Comment by mbernasocchi** [comment]
@Xpirix the UX looks great, but I would maybe replace the shopping cart with a T-shirt or a mug (or...) , if not it looks like qgis.org has suddenly turned into a shop

**Comment by anitagraser** [comment]
When the button expands to the right, how does the page react if there is little space left in the window (i.e. just before it turns into the version with hamburger menu)?

**Comment by Xpirix** [comment]
> @Xpirix the UX looks great, but I would maybe replace the shopping cart with a T-shirt or a mug (or...) , if not it looks like qgis.org has suddenly turned into a shop

Thanks for the suggestion @mbernasocchi, I've changed the icon with a mug icon. Also, I've replaced the text "Shop" with "Goodies" to be more accurate. Please find attached a screen record of the fix.

> When the button expands to the right, how does the page react if there is little space left in the window (i.e. just before it turns into the version with hamburger menu)?

It's a good question @anitagraser, currently, the button has a fixed space where it can expand even if the window is resized (Please see the attached screenshot). When it turns into the hamburger version, it will be always expanded.


https://github.com/user-attachments/assets/1bf43d4d-0b65-4414-a3f7-fd807dd01ba3

**Pull request merged**
